/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fty_utils_RtcmUtil */

#ifndef _Included_com_fty_utils_RtcmUtil
#define _Included_com_fty_utils_RtcmUtil
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jbyteArray JNICALL Java_com_fty_utils_RtcmUtil_passStructToJava
  (JNIEnv *, jclass);


JNIEXPORT jint JNICALL Java_com_fty_utils_RtcmUtil_passObjToNative
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
